### ISSUE TITLE
Face unexpected error after running

### ISSUE THREAD

**Issue by mittalyashu** [postcss/gulp-postcss#132]
Face this error after running.

```
at Gulp.<anonymous> (C:\Users\YASHU\Desktop\gulp\gulpfile.js:11:11)
    at module.exports (C:\Users\YASHU\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\YASHU\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\YASHU\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\YASHU\node_modules\orchestrator\index.js:134:8)
    at Gulp.<anonymous> (C:\Users\YASHU\node_modules\gulp\index.js:36:18)
    at Gaze.<anonymous> (C:\Users\YASHU\node_modules\glob-watcher\index.js:18:14)
    at emitTwo (events.js:106:13)
    at Gaze.emit (events.js:191:7)
    at Gaze.emit (C:\Users\YASHU\node_modules\gaze\lib\gaze.js:129:32)
```

**Comment by w0rm** [comment]
The aforementioned stack trace doesn't contain gulp-postcss, either this information is not enough or the problem lies somewhere else.
