### ISSUE TITLE
css.eachAtRule is not a function

### ISSUE THREAD

**Issue by sfunaro** [postcss/gulp-postcss#133]
Hi!
Trying to use postcss and I always get this error:
gulp parse-css-dev
[08:58:28] Using gulpfile ~/_Web/template-wp-2/gulpfile.js
[08:58:28] Starting 'parse-css-dev'...
[08:58:28] Finished 'parse-css-dev' after 10 ms

events.js:182
      throw er; // Unhandled 'error' event
      ^
TypeError: css.eachAtRule is not a function
    at Processor.remove (/Users/stefane/_Web/template-wp-2/node_modules/autoprefixer-core/lib/processor.js:77:11)
    at Autoprefixer.postcss (/Users/stefane/_Web/template-wp-2/node_modules/autoprefixer-core/lib/autoprefixer.js:70:33)
    at /Users/stefane/_Web/template-wp-2/node_modules/autoprefixer-core/lib/autoprefixer.js:4:61
    at LazyResult.run (/Users/stefane/_Web/template-wp-2/node_modules/postcss/lib/lazy-result.js:270:20)
    at LazyResult.asyncTick (/Users/stefane/_Web/template-wp-2/node_modules/postcss/lib/lazy-result.js:185:32)
    at LazyResult.asyncTick (/Users/stefane/_Web/template-wp-2/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/Users/stefane/_Web/template-wp-2/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/Users/stefane/_Web/template-wp-2/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/Users/stefane/_Web/template-wp-2/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/Users/stefane/_Web/template-wp-2/node_modules/postcss/lib/lazy-result.js:197:22)

The code is:
`
var gulp = require('gulp');
var autoprefixer = require('autoprefixer');
var cssnext = require('postcss-cssnext');
var postcss      = require('gulp-postcss');

gulp.task('parse-css-dev', function () {
	var plugins = [
		cssnext,
		autoprefixer({browsers: ['last 2 versions']})
	];
	return gulp.src("screen.css")
		.pipe(postcss(plugins))
		.pipe(gulp.dest("./test"));
});`

Versions (should be up to date):
"gulp": "^3.9.1",
"gulp-postcss": "^7.0.0",
"postcss-cssnext": "^3.0.2",
"autoprefixer": "^4.0.0",
Node: v8.0.0
Gulp: 3.9.1

I tried using: 
- only cssnext or only autoprefixer (so it's not one of them)
- passing only one plugin directly instead of an array
- using a css file with only one simple style in it
- using different paths

Is it my code or a problem with postcss ?
Thanks!

**Comment by TrySound** [comment]
@sfunaro Looks like you use too old version of autoprefixer (currently 7).

**Comment by sfunaro** [comment]
Haaaa! I switched from gulp-autoprefixer to autoprefixer, without changing the version!!! THANKS!
