### ISSUE TITLE
Error: Cannot find module 'autoprefixer-core'

### ISSUE THREAD

**Issue by verpixelt** [postcss/gulp-postcss#47]
I followed the instructions in your readme and it ends up with this error message:
```
Error: Cannot find module 'autoprefixer-core'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/verpixelt/projects/gulp-boilerplate/gulpfile.js:26:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by TrySound** [comment]
@verpixelt It's not gulp-postcss issue. Maybe you forgot to `npm i autoprefixer-core`?
Also I recommend to use `autoprefixer` module instead of `autoprefixer-core`. The last will be deprecated soon.

**Comment by verpixelt** [comment]
Might be the issue. Would be good to add this as a dependency to the README file (at least make it clearer).

**Comment by TrySound** [comment]
@verpixelt `Cannot find module 'autoprefixer-core'` means you do require without downloaded module. You require nothing.

**Comment by w0rm** [comment]
Yeah, maybe a line that says that you have to install processors separately, with a link to a list of them will be helpful.

**Comment by verpixelt** [comment]
Thanks @w0rm :) :+1:  That's really helpful! ☀️
