### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by gibbok** [postcss/gulp-postcss#79]
Running `gulp-postcss` using `Task Runner Explorer` in Visual Studio 2015 throws the following error.

It happens only when gulp task is executed from Visual Studio 2015 and does not happen when using `Command Prompt`.

Platform: Window 8.1
Node: v4.4.2

Error details:

```
Process terminated with code 8.
C:\xxx\node_modules\gulp-postcss\node_modules\postcss\lib\lazy-result.js:157
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined
    at LazyResult.async (xxx\node_modules\gulp-postcss\node_modules\postcss\lib\lazy-result.js:157:31)
    at LazyResult.then (xxx\node_modules\gulp-postcss\node_modules\postcss\lib\lazy-result.js:79:21)
    at Transform.stream._transform (xxx\node_modules\gulp-postcss\index.js:49:8)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at Transform.Writable.write (_stream_writable.js:182:11)
    at write (xxx\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (xxx\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)
```

**Comment by TrySound** [comment]
@gibbok 
https://github.com/postcss/postcss/issues/643#issuecomment-158568434
